.Dd June 11, 2026
.Dt LIBFWSI 3
.Os
.Sh NAME
.Nm libfwsi.h
.Nd Library to access the Windows Shell Item format
.Sh SYNOPSIS
.In libfwsi.h
.Pp
Support functions
.nf
.Ft const char *
.Fo libfwsi_get_version
.Fa "void"
.Fc
.fi
.Pp
Notify functions
.nf
.Ft void
.Fo libfwsi_notify_set_verbose
.Fa "int verbose"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_notify_set_stream
.Fa "FILE *stream"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_notify_stream_open
.Fa "const char *filename"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_notify_stream_close
.Fa "libfwsi_error_t **error"
.Fc
.fi
.Pp
Error functions
.nf
.Ft void
.Fo libfwsi_error_free
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_error_fprint
.Fa "libfwsi_error_t *error"
.Fa "FILE *stream"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_error_sprint
.Fa "libfwsi_error_t *error"
.Fa "char *string"
.Fa "size_t size"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_error_backtrace_fprint
.Fa "libfwsi_error_t *error"
.Fa "FILE *stream"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_error_backtrace_sprint
.Fa "libfwsi_error_t *error"
.Fa "char *string"
.Fa "size_t size"
.Fc
.fi
.Pp
Item list functions
.nf
.Ft int
.Fo libfwsi_item_list_initialize
.Fa "libfwsi_item_list_t **item_list"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_item_list_free
.Fa "libfwsi_item_list_t **item_list"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_item_list_copy_from_byte_stream
.Fa "libfwsi_item_list_t *item_list"
.Fa "const uint8_t *byte_stream"
.Fa "size_t byte_stream_size"
.Fa "int ascii_codepage"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_item_list_get_data_size
.Fa "libfwsi_item_list_t *item_list"
.Fa "size_t *data_size"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_item_list_get_number_of_items
.Fa "libfwsi_item_list_t *item_list"
.Fa "int *number_of_items"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_item_list_get_item
.Fa "libfwsi_item_list_t *item_list"
.Fa "int item_index"
.Fa "libfwsi_item_t **item"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.Pp
Item functions
.nf
.Ft int
.Fo libfwsi_item_initialize
.Fa "libfwsi_item_t **item"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_item_free
.Fa "libfwsi_item_t **item"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_item_copy_from_byte_stream
.Fa "libfwsi_item_t *item"
.Fa "const uint8_t *byte_stream"
.Fa "size_t byte_stream_size"
.Fa "int ascii_codepage"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_item_get_type
.Fa "libfwsi_item_t *item"
.Fa "int *type"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_item_get_class_type
.Fa "libfwsi_item_t *item"
.Fa "uint8_t *class_type"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_item_get_signature
.Fa "libfwsi_item_t *item"
.Fa "uint32_t *signature"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_item_get_data_size
.Fa "libfwsi_item_t *item"
.Fa "size_t *data_size"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_item_get_delegate_folder_identifier
.Fa "libfwsi_item_t *item"
.Fa "uint8_t *guid_data"
.Fa "size_t guid_data_size"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_item_get_number_of_extension_blocks
.Fa "libfwsi_item_t *item"
.Fa "int *number_of_extension_blocks"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_item_get_extension_block
.Fa "libfwsi_item_t *item"
.Fa "int extension_block_index"
.Fa "libfwsi_extension_block_t **extension_block"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.Pp
Root folder item functions
.nf
.Ft int
.Fo libfwsi_root_folder_get_shell_folder_identifier
.Fa "libfwsi_item_t *root_folder"
.Fa "uint8_t *guid_data"
.Fa "size_t guid_data_size"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.Pp
Volume item functions
.nf
.Ft int
.Fo libfwsi_volume_get_utf8_name_size
.Fa "libfwsi_item_t *volume"
.Fa "size_t *utf8_string_size"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_volume_get_utf8_name
.Fa "libfwsi_item_t *volume"
.Fa "uint8_t *utf8_string"
.Fa "size_t utf8_string_size"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_volume_get_utf16_name_size
.Fa "libfwsi_item_t *volume"
.Fa "size_t *utf16_string_size"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_volume_get_utf16_name
.Fa "libfwsi_item_t *volume"
.Fa "uint16_t *utf16_string"
.Fa "size_t utf16_string_size"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_volume_get_identifier
.Fa "libfwsi_item_t *volume"
.Fa "uint8_t *guid_data"
.Fa "size_t guid_data_size"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_volume_get_shell_folder_identifier
.Fa "libfwsi_item_t *volume"
.Fa "uint8_t *guid_data"
.Fa "size_t guid_data_size"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.Pp
File entry item functions
.nf
.Ft int
.Fo libfwsi_file_entry_get_file_size
.Fa "libfwsi_item_t *file_entry"
.Fa "uint32_t *file_size"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_file_entry_get_modification_time
.Fa "libfwsi_item_t *file_entry"
.Fa "uint32_t *fat_date_time"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_file_entry_get_file_attribute_flags
.Fa "libfwsi_item_t *file_entry"
.Fa "uint32_t *file_attribute_flags"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_file_entry_get_utf8_name_size
.Fa "libfwsi_item_t *file_entry"
.Fa "size_t *utf8_string_size"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_file_entry_get_utf8_name
.Fa "libfwsi_item_t *file_entry"
.Fa "uint8_t *utf8_string"
.Fa "size_t utf8_string_size"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_file_entry_get_utf16_name_size
.Fa "libfwsi_item_t *file_entry"
.Fa "size_t *utf16_string_size"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_file_entry_get_utf16_name
.Fa "libfwsi_item_t *file_entry"
.Fa "uint16_t *utf16_string"
.Fa "size_t utf16_string_size"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.Pp
Network location item functions
.nf
.Ft int
.Fo libfwsi_network_location_get_utf8_location_size
.Fa "libfwsi_item_t *network_location"
.Fa "size_t *utf8_string_size"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_network_location_get_utf8_location
.Fa "libfwsi_item_t *network_location"
.Fa "uint8_t *utf8_string"
.Fa "size_t utf8_string_size"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_network_location_get_utf16_location_size
.Fa "libfwsi_item_t *network_location"
.Fa "size_t *utf16_string_size"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_network_location_get_utf16_location
.Fa "libfwsi_item_t *network_location"
.Fa "uint16_t *utf16_string"
.Fa "size_t utf16_string_size"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_network_location_get_utf8_description_size
.Fa "libfwsi_item_t *network_location"
.Fa "size_t *utf8_string_size"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_network_location_get_utf8_description
.Fa "libfwsi_item_t *network_location"
.Fa "uint8_t *utf8_string"
.Fa "size_t utf8_string_size"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_network_location_get_utf16_description_size
.Fa "libfwsi_item_t *network_location"
.Fa "size_t *utf16_string_size"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_network_location_get_utf16_description
.Fa "libfwsi_item_t *network_location"
.Fa "uint16_t *utf16_string"
.Fa "size_t utf16_string_size"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_network_location_get_utf8_comments_size
.Fa "libfwsi_item_t *network_location"
.Fa "size_t *utf8_string_size"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_network_location_get_utf8_comments
.Fa "libfwsi_item_t *network_location"
.Fa "uint8_t *utf8_string"
.Fa "size_t utf8_string_size"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_network_location_get_utf16_comments_size
.Fa "libfwsi_item_t *network_location"
.Fa "size_t *utf16_string_size"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_network_location_get_utf16_comments
.Fa "libfwsi_item_t *network_location"
.Fa "uint16_t *utf16_string"
.Fa "size_t utf16_string_size"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.Pp
Compressed folder functions
.nf
.Ft int
.Fo libfwsi_compressed_folder_get_utf8_name_size
.Fa "libfwsi_item_t *compressed_folder"
.Fa "size_t *utf8_string_size"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_compressed_folder_get_utf8_name
.Fa "libfwsi_item_t *compressed_folder"
.Fa "uint8_t *utf8_string"
.Fa "size_t utf8_string_size"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_compressed_folder_get_utf16_name_size
.Fa "libfwsi_item_t *compressed_folder"
.Fa "size_t *utf16_string_size"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_compressed_folder_get_utf16_name
.Fa "libfwsi_item_t *compressed_folder"
.Fa "uint16_t *utf16_string"
.Fa "size_t utf16_string_size"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.Pp
Control panel category functions
.nf
.Ft int
.Fo libfwsi_control_panel_category_get_identifier
.Fa "libfwsi_item_t *control_panel_category"
.Fa "uint32_t *identifier"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.Pp
Control panel item functions
.nf
.Ft int
.Fo libfwsi_control_panel_item_get_identifier
.Fa "libfwsi_item_t *control_panel_item"
.Fa "uint8_t *guid_data"
.Fa "size_t guid_data_size"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.Pp
Users property view functions
.nf
.Ft int
.Fo libfwsi_users_property_view_get_known_folder_identifier
.Fa "libfwsi_item_t *users_property_view"
.Fa "uint8_t *guid_data"
.Fa "size_t guid_data_size"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_users_property_view_get_property_store_data_size
.Fa "libfwsi_item_t *users_property_view"
.Fa "size_t *data_size"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_users_property_view_copy_property_store_data
.Fa "libfwsi_item_t *users_property_view"
.Fa "uint8_t *data"
.Fa "size_t data_size"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.Pp
Extension block functions
.nf
.Ft int
.Fo libfwsi_extension_block_free
.Fa "libfwsi_extension_block_t **extension_block"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_extension_block_get_signature
.Fa "libfwsi_extension_block_t *extension_block"
.Fa "uint32_t *signature"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_extension_block_get_data_size
.Fa "libfwsi_extension_block_t *extension_block"
.Fa "size_t *data_size"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.Pp
File entry extension functions
.nf
.Ft int
.Fo libfwsi_file_entry_extension_get_creation_time
.Fa "libfwsi_extension_block_t *file_entry_extension"
.Fa "uint32_t *fat_date_time"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_file_entry_extension_get_access_time
.Fa "libfwsi_extension_block_t *file_entry_extension"
.Fa "uint32_t *fat_date_time"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_file_entry_extension_get_file_reference
.Fa "libfwsi_extension_block_t *file_entry_extension"
.Fa "uint64_t *file_reference"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_file_entry_extension_get_utf8_long_name_size
.Fa "libfwsi_extension_block_t *file_entry_extension"
.Fa "size_t *utf8_string_size"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_file_entry_extension_get_utf8_long_name
.Fa "libfwsi_extension_block_t *file_entry_extension"
.Fa "uint8_t *utf8_string"
.Fa "size_t utf8_string_size"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_file_entry_extension_get_utf16_long_name_size
.Fa "libfwsi_extension_block_t *file_entry_extension"
.Fa "size_t *utf16_string_size"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_file_entry_extension_get_utf16_long_name
.Fa "libfwsi_extension_block_t *file_entry_extension"
.Fa "uint16_t *utf16_string"
.Fa "size_t utf16_string_size"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_file_entry_extension_get_utf8_localized_name_size
.Fa "libfwsi_extension_block_t *file_entry_extension"
.Fa "size_t *utf8_string_size"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_file_entry_extension_get_utf8_localized_name
.Fa "libfwsi_extension_block_t *file_entry_extension"
.Fa "uint8_t *utf8_string"
.Fa "size_t utf8_string_size"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_file_entry_extension_get_utf16_localized_name_size
.Fa "libfwsi_extension_block_t *file_entry_extension"
.Fa "size_t *utf16_string_size"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfwsi_file_entry_extension_get_utf16_localized_name
.Fa "libfwsi_extension_block_t *file_entry_extension"
.Fa "uint16_t *utf16_string"
.Fa "size_t utf16_string_size"
.Fa "libfwsi_error_t **error"
.Fc
.fi
.Pp
Shell folder identifier functions
.nf
.Ft const char *
.Fo libfwsi_shell_folder_identifier_get_name
.Fa "const uint8_t *shell_folder_identifier"
.Fc
.fi
.Sh DESCRIPTION
The
.Fn libfwsi_get_version
function is used to retrieve the library version.
.Sh RETURN VALUES
Most of the functions return NULL or \-1 on error, dependent on the return \
type.
For the actual return values see
.In libfwsi.h .
.Sh ENVIRONMENT
None
.Sh FILES
None
.Sh SEE ALSO
.In libfwsi.h
.Sh AUTHORS
.An Joachim Metz <joachim.metz@gmail.com>
.Sh BUGS
Please report bugs of any kind on the project issue tracker: \
https://github.com/libyal/libfwsi/issues
.Sh COPYRIGHT
Copyright (C) 2010-2026, Joachim Metz <joachim.metz@gmail.com>.
.sp
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A \
PARTICULAR PURPOSE.
