= Windows Shell Item format specification
Analysis of the Windows Shell Item format

[yellow-background]*

:numbered!:
[abstract]
== Summary
The Windows Shell uses Shell Items (Shell item list) to identify items within 
the Windows Folder Hierarchy. A Shell Item list is much like a path, and is 
unique to its parent folder. The format of the Shell Item is undocumented and 
varies between Windows versions. This specification is based on earlier work on 
the format and was complimented by reverse engineering.

This document is intended as a working document for the Windows Shell Items 
format specification. Which should allow existing Open Source forensic tooling 
to be able to process this file type.

[preface]
== Document information
[cols="1,5"]
|===
| Author(s): | Joachim Metz <joachim.metz@gmail.com>
| Abstract: | This document contains information about the Windows Shell Item format.
| Classification: | Public
| Keywords: | Windows Shell Item
|===

[preface]
== License
....
Copyright (c) 2010-2014, Joachim Metz <joachim.metz@gmail.com>.
Permission is granted to copy, distribute and/or modify this document under the 
terms of the GNU Free Documentation License, Version 1.3 or any later version 
published by the Free Software Foundation; with no Invariant Sections, no 
Front-Cover Texts, and no Back-Cover Texts. A copy of the license is included 
in the section entitled "GNU Free Documentation License".
....

[preface]
== Revision history
[cols="1,1,1,5",options="header"]
|===
| Version | Author | Date | Comments
| 0.0.1 | J.B. Metz | July 2010 | Initial version based on earlier work.
| 0.0.2 | J.B. Metz | August 2010 | Additional Windows 7 information.
| 0.0.3 | J.B. Metz | August 2010 | Additional known folder identifiers
| 0.0.4 | J.B. Metz | August 2010 | Additional shell item information, control panel shell item information, folder type and Windows 7 shell library information.
| 0.0.5 | J.B. Metz | August 2010 | Additional shell column property information.
| 0.0.6 | J.B. Metz | September 2010 | Merged directory name and filename shell items into file entry shell item. +
Added information about NTFS file reference. +
Corrected references.
| 0.0.7 | J.B. Metz | January 2011 | License version update +
Additional Windows 2000 and 2003 information.
| 0.0.8 | J.B. Metz | March 2012 | Added information about known folder identifiers. +
Found additional shell items in test files `[LOPEZ10]`.
| 0.0.9 | J.B. Metz | May 2012 | Updates for Windows 8 Consumer Preview.
| 0.0.10 | J.B. Metz | August 2012 | New findings regarding shell property sheets (formerly indicated as shell column properties) with thanks to H. Carvey and J. Moore.
| 0.0.11 | J.B. Metz | February 2013 | Additional information regarding Windows 95 shell item types.
| 0.0.12 | J.B. Metz | February 2013 | Additional information regarding Windows 95 shell item types. Merged file entry name and file entry seem to be the same type.
| 0.0.13 | J.B. Metz | February 2013 | Renamed the shell property sheets (formerly indicated as shell column properties) to property store as indicated in the LNK documentation.
| 0.0.14 | J.B. Metz | June 2013 | Additional information regarding regarding class type indicators. +
Additional findings regarding class type indicator flag 0x80.
| 0.0.15 | J.B. Metz | June 2013 | New findings regarding shell item type 0x1f, 0x2f and 0x74.
| 0.0.16 | J.B. Metz | June 2013 | New findings regarding Windows 98 shell items, shell item class 0x40, extension blocks and delegate items. Special thanks to J. Sánchez López for revisiting his previous findings.
| 0.0.17 | J.B. Metz | June 2013 | New findings regarding shell item type 0x00 and 0xff with thanks to Eduardo P.
| 0.0.18 | J.B. Metz | June 2013 | New findings regarding shell item types 0x35, 0x4c, 0x61 and FTP sub shell items, and extension blocks.
| 0.0.19 | J.B. Metz | June 2013 | New findings regarding shell item type 0x00 and extension blocks. Moved Property store definitions to separate document.
| 0.0.20 | J.B. Metz | July 2013 | Renamed folder identifier shell item to root folder shell item and volume name shell item to volume shell item.
| 0.0.21 | J.B. Metz | October 2013 | New findings on Windows 8.1 with thanks to E. Zimmerman.
| 0.0.22 | J.B. Metz | July 2014 | Textual changes.
| 0.0.22 | J.B. Metz | July 2014 | New findings on Control Panel 0x01 shell item with thanks to E. Zimmerman.
| 0.0.23 | J.B. Metz | July 2014 | Found new file entry 0x32 shell item – SWN1. Added findings on the Acronis 0x52 shell item with thanks to D. Pullega and findings on MTP and MSC storage device shell items with thanks to N. Ibrahim.
| 0.0.24 | J.B. Metz | July 2014 | August 2014
| Additional information on file entry 0x32 shell item – SWN1 and property view shell items. New findings on extension block 0xbeef0025 with thanks to E. Zimmerman and findings on file entry 0x36 shell item with thanks to F. Picasso.
| 0.0.25 | J.B. Metz | August 2014 | Restructured document, textual changes and additional information on the CD burn, delegate, compressed folder and MTP storage device shell items and extension blocks with thanks to E. Zimmerman.
| 0.0.26 | J.B. Metz | August 2014 | Moved property set information to LIBWPS documentation. +
Updated information regarding the control panel CPL file and delegate shell item. +
Additional information regarding extension blocks 0xbeef0000, 0xbeef0001, 0xbeef0008 and 0xbeef0010 with thanks to E. Zimmerman.
| 0.0.27 | J.B. Metz | August 2014 | Textual changes. +
Updated information regarding the delegate shell item.
| 0.0.28 | J.B. Metz | September 2014 | Additional information regarding shell item 0x67 and extension block 0xbeef0021 with thanks to E. Zimmerman.
| 0.0.29 | J.B. Metz | October 2014 | Additional information regarding CDBurn shell item and extension blocks 0xbeef000b, 0xbeef000e and 0xbeef0016 with thanks to E. Zimmerman.
| 0.0.30 | J.B. Metz | December 2014 | Switched to asccidoc format.
|===

:numbered:
== Overview
The Windows Shell uses Shell Items (Shell Item list) to identify items within 
the Windows Folder Hierarchy. A Shell Item list is much like a path, and is 
unique to its parent folder. The format of the Shell Item is undocumented and 
varies between Windows versions.

[cols="1,5",options="header"]
|===
| Characteristics | Description
| Byte order | little-endian
| Date and time values | 
| Character strings | ASCII strings are Single Byte Character (SBC) or Multi Byte Character (MBC) string stored with a codepage. Sometimes referred to as ANSI string representation. +
Though technically maybe incorrect, this document will use term (extended) ASCII string. +
Unicode strings are stored in UTF-16 little-endian without the byte order mark (BOM).
|===

=== Test versions
The following version of programs were used to test the information within this 
document:

* Windows 95
* Windows 98
* [yellow-background]*
* TODO: Windows Me
* Windows NT4
* Windows 2000 (SP4)
* Windows XP (SP3)
* Windows 2003
* Windows Vista (SP0)
* Windows 2008
* Windows 7 (SP0)
* Windows 8
* [yellow-background]*TODO: Windows 2012*
* Windows 8.1

== Shell Item list
The Shell Item list (ITEMIDLIST) is variable of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | ... | | The Shell Item
| ... | 2 | 0 | Terminal identifier +
Signifies the end of the Shell Item list
|===

The shell items identifiers list consists of Shell Item terminated by the 
terminal identifier (an empty Shell Item).

=== Shell Item
The Shell Item (SHITEMID) is variable of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 2 | | The size of the shell item +
Includes the 2 bytes of the size itself, 0 if shell item is empty
3+| _Shell Item data_
| 2 | 1 | | Class type indicator
| 3 | ... | | Class type specific data
|===

[yellow-background]*Related class identifier CLSID_ShellItem?*

The class type indicator has proven not to be a foolproof indicator for all 
shell items, but it appears to be a strong one for others hence (for now) we 
divide the shell items into two categories:

* type indicator-base shell items
* signature-base shell items

== Type indicator-based shell items
===  Class type indicator
The class type indicator is a combination of a type, sub-type and flags.

[cols="1,1,5",options="header"]
|===
| Value | Related class identifier (CLSID) | Description
| 0x00 | | [yellow-background]*Unknown*
| 0x01 | | [yellow-background]*Unknown*
| | | 
| 0x17 | | [yellow-background]*Unknown*
| | | 
| 0x1e | CLSID_ShellDesktop | [yellow-background]*Not seen in wild but reason to believe it exists.*
| 0x1f | CLSID_ShellDesktop +
[yellow-background]*Likely IshellFolder interface?* | Root folder shell item
| | | 
| 0x20 – 0x2f | CLSID_MyComputer | Volume shell item +
See section: <<volume_shell_item,Volume shell item>>
| 0x30 – 0x3f | CLSID_ShellFSFolder | File entry shell item +
See section: <<file_entry_shell_item,File entry shell item>>
| 0x40 – 0x4f | [yellow-background]*CLSID_NetworkRoot* +
[yellow-background]*CLSID_NetworkPlaces* | Network location shell item +
See section: <<network_location_shell_item,Network location shell item>>
| | |
| 0x52 | | [yellow-background]*Compressed folder shell item* +
See section: <<compressed_folder_shell_item,Compressed folder shell item>>
| | | 
| 0x61 | CLSID_Internet | URI shell item
| | | 
| 0x70 | ControlPanel | [yellow-background]*Not seen in wild but reason to believe it exists.* +
[yellow-background]*item has no item data at offset 0x04*
| 0x71 | ControlPanel | ControlPanelTasks | Control Panel shell item
| 0x72 | Printers | [yellow-background]*Not seen in wild but reason to believe it exists.* +
[yellow-background]*Printers*
| 0x73 | CommonPlacesFolder | [yellow-background]*Not seen in wild but reason to believe it exists.*
| 0x74 | UsersFilesFolder | [yellow-background]*Unknown* +
[yellow-background]*Only seen as delegate item*
| | | 
| 0x76 | | [yellow-background]*Unknown*
| | | 
| 0x80 | | [yellow-background]*Unknown – different meaning per class type indicator?*
| | | 
| 0xff | | [yellow-background]*Unknown*
|===

[yellow-background]*Type 0x08 (with size of 6) is alias ?*
[yellow-background]*Type 0x0c is alias ?*

[yellow-background]*0x3a Name space object? Link blessing? My Computer (CRegFolder)?*

[yellow-background]*0x7b extension?*

[yellow-background]*What is the relationship between the root (first) shell 
item (0x1f/0x1e?) and the other shell items?*

=== Root folder shell item
The root folder shell item is variable of size and consists of the following 
values:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 2 | | The size of the shell item +
Includes the 2 bytes of the size itself
| 2 | 1 | 0x1f | Class type indicator
| 3 | 1 | | Sort index
| 4 | 16 | | Shell folder identifier +
Contains a GUID +
For a list of shell folder identifiers see: `[LIBFWSI-WIKI]`
3+| _Present if shell item size > 20 (seen in Windows 7)_
| 20 | ... | | Extension block 0xbeef0017 +
See section: <<extension_block_0xbeef0017,Extension block 0xbeef0017>>
|===

Shell item from Windows 7 ShellMRU (Search Home)
....
00000000: 1f 80 2e 81 43 93 37 1c  49 4a a1 2e 4b 2d 81 0d   ....C.7. IJ..K-..
00000010: 95 6b 46 00 01 00 17 00  ef be 00 00 00 00 01 00   .kF..... ........
00000020: 00 00 02 00 00 80 01 00  00 00 01 00 00 00 02 00   ........ ........
00000030: 00 00 00 00 00 00 00 00  00 00 02 00 00 00 00 00   ........ ........
00000040: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........
00000050: 00 00 00 00 00 00 14 00                            ........
....

==== Sort index

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x00 | | Internet Explorer
| 0x42 | | Libraries
| 0x44 | | Users
| 0x48 | | My Documents
| 0x50 | | My Computer
| 0x58 | | My Network Places/Network
| 0x60 | | Recycle Bin
| 0x68 | | Internet Explorer
| 0x70 | | [yellow-background]*Unknown*
| 0x80 | | My Games
|===

[yellow-background]*Common sort indexes matches info in oleview.exe*

=== [[volume_shell_item]]Volume shell item
The volume shell item is identified by a value of 0x20 after applying a bitmask 
of 0x70. The remaining bits in the class type indicator are presumed to be a 
sub-type or flags.

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x01 | | Has name
| 0x02 | | [yellow-background]*Unknown (0x23 C:, 0x2f C: or D:, 0x2a J:)*
| 0x04 | | [yellow-background]*Unknown (0x23 C:, 0x25 D:)*
| 0x08 | | Is removable media (0x23 C:, 0x29 A:, 0x2a J:)
|===

Values that have been seen: 0x23, 0x25, 0x29, 0x2a, 0x2e, 0x2f

The volume shell item is variable bytes of size and consists of the following 
values:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 2 | | The size of the shell item +
Includes the 2 bytes of the size itself
| 2 | 1 | | Class type indicator +
0x20 after applying a bitmask of 0x70
3+| _If class type indicator flag 0x01 (has name) is not set_
| 3 | 1 | [yellow-background]*Unknown (Flags)*
[yellow-background]*Seen 0x00, 0x1e, 0x80*
| 4 | 16 | [yellow-background]*Volume identifier?* +
Contains a GUID +
Control Panel and Printers folder identifier seen in windows 95 lnk
3+| _If class type indicator flag 0x01 (has name) is set_
| 3 | 20 | | Volume name +
ASCII string with end-of-string character +
Remaining bytes are filled with 0 byte values
| 23 | 2 | [yellow-background]*Unknown (icon index or file attributes?)*
3+ | _[yellow-background]*Present if shell item size > 25 (seen in Windows 7) or is this indicated by another value?*_
| 25 | 16 | | Shell folder identifier +
Contains a GUID +
For a list of shell folder identifiers see: `[LIBFWSI-WIKI]`
3+| _Present if shell item contains more data_
| ... | ... | | Extension block +
[yellow-background]*Seen extension block 0xbeef0025.* +
See section: <<extension_block_0xbeef0025,Extension block 0xbeef0025>>
|===

Found in Windows 7 BagMRU
....
00000000: 2f 44 3a 5c 00 00 00 00  00 00 00 00 00 00 00 00   /D:\.... ........
00000010: 00 00 00 00 00 01 01 05  8a eb fb ee be 42 44 80   ........ .....BD.
00000020: 4e 40 9d 6c 45 15 e9                               N@.lE..

00000000  32 00 2e 80 3a cc bf b4  2c db 4c 42 b0 29 7f e9  |2...:...,.LB.)..| 
00000010  9a 87 c6 41 1e 00 00 00  25 00 ef be 11 00 00 00  |...A....%.......| 
00000020  fa 66 a2 86 36 74 cf 01  2d 81 fe bc ba 9b cf 01  |.f..6t..-.......| 
00000030  14 00 00 00                                       |....| 

00000000  32 00 2e 80 90 e2 4d 37  3f 12 65 45 91 64 39 c4  |2.....M7?.eE.d9.| 
00000010  92 5e 46 7b 1e 00 00 00  25 00 ef be 11 00 00 00  |.^F{....%.......| 
00000020  fa 66 a2 86 36 74 cf 01  33 cb 2c 72 3b 74 cf 01  |.f..6t..3.,r;t..| 
00000030  14 00 00 00                                       |....| 
....

=== [[file_entry_shell_item]]File entry shell item
The file entry shell item is identified by a value of 0x30 after applying a 
bitmask of 0x70. The remaining bits in the class type indicator are presumed to 
be a sub-type or flags.

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x01 | | Is directory
| 0x02 | | Is file
| 0x04 | | Has Unicode strings
| 0x08 | [yellow-background]*Unknown (common item flag?)* +
[yellow-background]*Related to the common item dialog?*
| 0x80 | | Has class identifier
[yellow-background]*(related to junction?)*
|===

Values that have been seen: 0x30, 0x31, 0x32, 0x35, 0x36, 0xb1.
[yellow-background]*Possible other values: 0x38.*

According to `[LOPEZ10]` the value in the last two bytes of the shell can be 
used to find the offset of the extension block version and if this value is 
sane the file entry shell item contains an extension block (Windows XP or 
later) or otherwise the secondary name value (pre Windows XP).

==== File entry shell item – pre Windows XP
This version of the the file entry shell item is used by Windows versions 
predating Windows XP, e.g. Windows 95, Windows NT4, Windows 2000.

The file entry shell item is variable of size and consists of the following 
values:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 2 | | The size of the shell item +
Includes the 2 bytes of the size itself
| 2 | 1 | | Class type indicator +
0x30 after applying a bitmask of 0x70
| 3 | 1 | 0 | [yellow-background]*Unknown (Empty value)
| 4 | 4 | | File size +
[yellow-background]*What about > 32-bit file sizes?*
| 8 | 4 | | Last modification date and time +
Contains a FAT date and time in UTC
| 12 | 2 | | File attribute flags +
Contains the lower 16-bit part of the file attribute flags. +
See section: <<file_attribute_flags,File attribute flags>> +
[yellow-background]*What does 0x8000 represent? Seen in windows 98 lnk.*
| 14 | ... | | Primary name +
Depending on flag 0x04 an ASCII or UTF-16 little-endian string with end-of-string character. +
Also see below.
| ... | ... | | Secondary name +
Depending on flag 0x04 an ASCII or UTF-16 little-endian string with end-of-string character. +
Also see below.
3+| _If class type indicator flag 0x80 is set_
| ... | 16 | | Shell folder identifier +
Contains a GUID +
For a list of shell folder identifiers see: `[LIBFWSI-WIKI]`
|===

The primary name contains the long name if available otherwise it contains the 
short name. If the primary name contains the long name the secondary name 
contains the short name otherwise it is empty (consist of a single 
end-of-string character).

[yellow-background]*It is unknown when Unicode string support was added but it 
is assumed that it also applies to pre Windows XP file entry shell item.*

On Windows 95 for type 0x30 (without flags) none of the values in the first 11 
bytes after the type indicator are set.

==== File entry shell item – Windows XP and later
This version of the the file entry shell item is used by Windows XP and later 
versions.

The file entry shell item is variable of size and consists of the following 
values:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 2 | | The size of the shell item +
Includes the 2 bytes of the size itself
| 2 | 1 | | Class type indicator +
0x30 after applying a bitmask of 0x70
| 3 | 1 | 0 | [yellow-background]*Unknown (Empty value)
| 4 | 4 | | File size +
[yellow-background]*What about > 32-bit file sizes?*
| 8 | 4 | | Last modification date and time +
Contains a FAT date and time in UTC
| 12 | 2 | | File attribute flags +
Contains the lower 16-bit part of the file attribute flags. +
See section: <<file_attribute_flags,File attribute flags>>
| 14 | ... | | Primary name +
Depending on flag 0x04 an ASCII or UTF-16 little-endian string with end-of-string character. +
This value is 16-bit aligned, so for ASCII strings it can contain an additional zero byte. +
Also see below.
| ... | ... | | Extension block 0xbeef0004 +
This value contains the the size of the extension block or 0 if not set +
See section: <<extension_block_0xbeef004,File entry extension block (0xbeef0004)>>
3+| _Present if shell item contains more data [yellow-background]*(and flag 0x80 is not set?)* (seen in Windows 2003)_
| ... | ... | | Extension block +
[yellow-background]*Seen extension block 0xbeef0005, 0xbeef0006 and 0xbeef001a.*
3+| _If class type indicator flag 0x80 is set_
| ... | ... | | Extension block 0xbeef0003 +
See section: <<extension_block_0xbeef0003,Extension block 0xbeef0003>>
|===

The primary name often contains the short name, but can contain the long name 
as well e.g. when class indicator flag 0x04 is set.

[NOTE]
The date and time values do not always seem to be set.

==== File entry shell item - SolidWorks
Seen in Windows 7 in LastVisitedPidMRU and LNK files after shell item 0xb1 with 
extension block 0xbeef0003 which contains the SolidWorks Enterprise PDM CLSID: 
{0bd8e793-d371-11d1-b0b5-0060972919d7}.

The file entry shell item is variable of size and consists of the following 
values:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 2 | | The size of the shell item +
Includes the 2 bytes of the size itself
| 2 | 1 | [yellow-background]*Seen: 0x32* | Class type indicator +
0x30 after applying a bitmask of 0x70
| 3 | 1 | 0 | [yellow-background]*Unknown (Empty value)*
| 4 | 4 | [yellow-background]*Seen: 0* | File size +
[yellow-background]*What about > 32-bit file sizes?*
| 8 | 4 | [yellow-background]*Seen: 0* | Last modification date and time +
Contains s FAT date and time in UTC
| 12 | 2 | [yellow-background]*Seen: 0* | File attribute flags +
Contains the lower 16-bit part of the file attribute flags. +
See section: <<file_attribute_flags,File attribute flags>>
| 14 | ... | | Primary name +
UTF-16 little-endian string with end-of-string character.
| ... | 2 | [yellow-background]*Seen: 0* | Extension block +
This value contains the the size of the extension block or 0 if not set
| ... | 7 | "S.W.N.1" | Signature
| ... | 1 | | [yellow-background]*The file entry type?* +
[yellow-background]*0x01 => directory* +
[yellow-background]*0x02= > file* +
[yellow-background]*Likely part of signature*
| ... | 4 | | [yellow-background]*Unknown*
| ... | 4 | | [yellow-background]*Unknown*
| ... | 8 | [yellow-background]*Seen: 2* | [yellow-background]*Unknown*
| ... | 6 | [yellow-background]*Seen: 0* | [yellow-background]*Unknown (Empty values)*
|===

==== Notes
[yellow-background]*File date and time values populated from WIN32_FIND_DATA?*

[yellow-background]*Part before the extension block FolderItem typelib interface?*

[cols="1,1,5",options="header"]
|===
| Class identifier (CLSID) | Related interface identifier(s) (IID) | Related class
| CLSID_FolderItem | IID_IPersistFolder | 
|===

=== [[network_location_shell_item]]Network location shell item
The network location shell item is identified by a value of 0x40 after applying 
a bitmask of 0x70. The remaining bits in the class type indicator are presumed 
to be a sub-type or flags.

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x01 | | Domain/Workgroup name
| 0x02 | | Server UNC path
| 0x03 | | Share UNC path
| | | 
| 0x06 | | Microsoft Windows Network
| 0x07 | | Entire Network
| | | 
| [yellow-background]*0x0d* | [yellow-background]*NetworkPlaces* | [yellow-background]*if resource display type is generic or root*
| [yellow-background]*0x0e* | [yellow-background]*NetworkPlaces* | [yellow-background]*if resource display type is server*
| | | 
| 0x80 | | [yellow-background]*Unknown*
|===

Values that have been seen: 0x41, 0x42, 0x46, 0x47, 0x4c, 0xc3

The Network location shell item is variable of size and consists of the 
following values:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 2 | | The size of the shell item +
Includes the 2 bytes of the size itself
| 2 | 1 | | Class type indicator +
0x40 after applying a bitmask of 0x70
| 3 | 1 | | [yellow-background]*Unknown* +
[yellow-background]*0x00, 0x01 (in UNC path), 0x03*
| 4 | 1 | | Flags +
[yellow-background]*0x01* +
[yellow-background]*0x02* +
[yellow-background]*0x04* +
0x40 => has comments +
0x80 => has description
| 5 | ... | | Location +
Contains the network name or UNC path +
ASCII string with end-of-string character
3+| _If flag 0x80 is set_
| ... | ... | | Description +
ASCII string with end-of-string character
3+| _If flag 0x40 is set_
| ... | ... | | Comments +
ASCII string with end-of-string character
3+| _[yellow-background]*If size > ?*_
| ... | ... | | [yellow-background]*Unknown* +
[yellow-background]*0x0000* +
[yellow-background]*0x0002* +
[yellow-background]*0x000042*
|===

=== [[compressed_folder_shell_item]]Compressed folder shell item
The compressed folder shell item is variable of size and consists of the 
following values:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 2 | | The size of the shell item +
Includes the 2 bytes of the size itself
| 2 | 1 | 0x52 | Class type indicator
| 3 | 1 | [yellow-background]*Seen: 0x67* | [yellow-background]*Unknown*
| 4 | 2 | [yellow-background]*Seen: 0xacb1* | [yellow-background]*Unknown (flags or signature of some kind)*
3+| _[yellow-background]*Controlled by one of the flags?*_
| 6 | 4 | [yellow-background]*Seen: 1, 2, 3* | [yellow-background]*Unknown*
| 10 | 8 | | [yellow-background]*Unknown (empty values)*
| 18 | 4 | [yellow-background]*Seen: 0x10, 0x11, 0x16* | [yellow-background]*Unknown*
| 22 | 4 | | [yellow-background]*Unknown* +
[yellow-background]*Possibly used for higher precision timestamps*
| 26 | 4 | | [yellow-background]*Unknown (date and time)*
Contains a FAT date and time in UTC, or 0 if not set
| 30 | 4 | | [yellow-background]*Unknown*
[yellow-background]*Possibly used for higher precision timestamps*
| 34 | 4 | | [yellow-background]*Unknown (date and time)* +
Contains a FAT date and time in UTC, or 0 if not set
| 38 | 8 | 0 | [yellow-background]*Unknown (empty values)*
3+| _Common_
| 46 | 4 | | [yellow-background]*Unknown string size* +
Contains the number of characters which includes the end-of-string character +
An empty strings is stored with a size of 1
| 50 | ... | | [yellow-background]*Unknown string (file entry name?)* +
UTF-16 little-endian string with end-of-string character.
| ... | 4 | | [yellow-background]*Unknown string size* +
Contains the number of characters which includes the end-of-string character +
An empty strings is stored with a size of 1
| ... | ... | | [yellow-background]*Unknown string* +
UTF-16 little-endian string with end-of-string character.
| ... | 4 | | Full path string size +
Contains the number of characters which includes the end-of-string character +
An empty strings is stored with a size of 1
| ... | ... | | Full path string +
UTF-16 little-endian string with end-of-string character.
| ... | 4 | | [yellow-background]*Unknown string size* +
Contains the number of characters which includes the end-of-string character +
An empty strings is stored with a size of 1
| ... | ... | | [yellow-background]*Unknown string* +
UTF-16 little-endian string with end-of-string character.
|===

....
00000000: 67 b1 ac 02 00 00 00 00  00 00 00 00 00 00 00 16   g....... ........ 
00000010: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........ 
00000020: 00 00 00 00 00 00 00 00  00 00 00 03 00 00 00 43   ........ .......C 
00000030: 00 3a 00 00 00 03 00 00  00 43 00 3a 00 00 00 03   .:...... .C.:.... 
00000040: 00 00 00 43 00 3a 00 00  00 01 00 00 00 00 00      ...C.:.. ....... 

00000000: 67 b1 ac 01 00 00 00 00  00 00 00 00 00 00 00 00   g....... ........ 
00000010: 00 00 00 00 00 00 00 00  00 00 00 00 00 03 de 3d   ........ .......= 
00000020: 27 74 42 00 00 00 00 00  00 00 00 25 00 00 00 30   'tB..... ...%...0 
00000030: 00 43 00 32 00 46 00 34  00 45 00 45 00 42 00 2d   .C.2.F.4 .E.E.B.- 
00000040: 00 30 00 42 00 30 00 39  00 2d 00 34 00 43 00 39   .0.B.0.9 .-.4.C.9 
00000050: 00 32 00 2d 00 39 00 30  00 44 00 31 00 2d 00 34   .2.-.9.0 .D.1.-.4 
00000060: 00 31 00 39 00 31 00 30  00 41 00 31 00 41 00 41   .1.9.1.0 .A.1.A.A 
00000070: 00 46 00 42 00 33 00 00  00 0d 00 00 00 4d 00 79   .F.B.3.. .....M.y 
00000080: 00 20 00 44 00 6f 00 63  00 75 00 6d 00 65 00 6e   . .D.o.c .u.m.e.n 
00000090: 00 74 00 73 00 00 00 01  00 00 00 00 00 01 00 00   .t.s.... ........ 
000000a0: 00 00 00                                           ... 

00000000        67 45 23 01 00 00  36 00 37 00 45 00 46 00  |R.gE#...6.7.E.F.| 
00000010  33 00 38 00 38 00 31 00  2d 00 35 00 33 00 35 00  |3.8.8.1.-.5.3.5.| 
00000020  36 00 2d 00 34 00 65 00  61 00 35 00 2d 00 38 00  |6.-.4.e.a.5.-.8.| 
00000030  43 00 42 00 45 00 2d 00  43 00 43 00 46 00 38 00  |C.B.E.-.C.C.F.8.| 
00000040  33 00 42 00 46 00 41 00  36 00 43 00 42 00 34 00  |3.B.F.A.6.C.B.4.| 
00000050  00 00                                             |....| 
00000054 
....

=== URI shell item
The URI shell item is variable of size and consists of the following values:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 2 | | The size of the shell item +
Includes the 2 bytes of the size itself
| 2 | 1 | 0x61 | Class type indicator
| 3 | 1 | [yellow-background]*Flags* +
[yellow-background]*0x01* +
[yellow-background]*0x02* +
0x80 set if URI string in Unicode
| 4 | 2 | | Size of data +
Includes the 2 bytes of the size itself 0 if no data +
3+| _If size of data > 0 [yellow-background]*(or is this controlled by flag 0x01 or 0x02 ?*_
| ... | 4 | | [yellow-background]*Unknown*
| ... | 4 | | [yellow-background]*Unknown*
| ... | 8 | | [yellow-background]*Unknown timestamp* +
Contains a FILETIME
| ... | 4 | | [yellow-background]*Unknown* +
[yellow-background]*Seen: 0x00000000, 0xffffffff*
| ... | 12 | | [yellow-background]*Unknown (Empty values)*
| ... | 4 | | [yellow-background]*Unknown*
| ... | 4 | | String1 data size +
Value in bytes
| ... | ... | | String1 data +
Depending on flag 0x80 an ASCII or UTF-16 little-endian string with end-of-string character. The string is 4-byte aligned unused bytes are filled with 0-byte values. Therefore an empty string is  stored as 4x 0-byte values.
| ... | 4 | | String2 data size +
Value in bytes
| ... | 4 | | String2 data +
Depending on flag 0x80 an ASCII or UTF-16 little-endian string with end-of-string character. The string is 4-byte aligned unused bytes are filled with 0-byte values. Therefore an empty string is  stored as 4x 0-byte values.
| ... | 4 | | String3 data size +
Value in bytes
| ... | 4 | | String3 data +
Depending on flag 0x80 an ASCII or UTF-16 little-endian string with end-of-string character. The string is 4-byte aligned unused bytes are filled with 0-byte values. Therefore an empty string is  stored as 4x 0-byte values.
3+| _Common_
| ... | 2 | 0 | [yellow-background]*Unknown (size of data?)*
| ... | ... | | URI string +
Depending on flag 0x80 an ASCII or UTF-16 little-endian string with end-of-string character. +
Not always present is this controlled by flag 0x01 or 0x02 ?
| ... | 2 | | [yellow-background]*Unknown (Empty values)* +
Present if shell item contains more data (Seen in Vista in combination with MSIE 7)
| ... | 4 | | Extension block 0xbeef0014 +
See section: <<extension_block_0xbeef0014,Extension block 0xbeef0014>>
|===

==== FTP sub shell item
Seen after 0x61 shell item type with ftp URI.

The ftp sub shell item is variable of size and consists of the following values:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 2 | | The size of the shell item +
Includes the 2 bytes of the size itself
| 2 | 1 | | [yellow-background]*Class type indicator?* +
[yellow-background]*Seen: 0x17, 0x30, 0x5b, 0xb5, 0xb7, 0xb9, 0xba, 0xc2, 0xc4, 0xe6*
| 3 | 1 | | [yellow-background]*Unknown* +
[yellow-background]*Seen: 0x00, 0x06, 0x09*
| 4 | 2 | | [yellow-background]*Unknown* +
[yellow-background]*If 0 no string padding?*
| 6 | 4 | | [yellow-background]*Unknown* +
[yellow-background]*Seen: 0x00000005, 0x00000009*
| 10 | 4 | | [yellow-background]*Unknown (flags?)* +
[yellow-background]*Seen: 0x00000080, 0x00000090*
| 14 | 24 | | [yellow-background]*Unknown (empty values)*
| 38 | ... | | String +
ASCII string with end-of-string character +
Sometimes is 4-byte aligned unused bytes are filled with 0-byte values?
| ... | ... | | Unicode string +
UTF-16 little-endian string with end-of-string character +
Sometimes is 4-byte aligned unused bytes are filled with 0-byte values?
| ... | ... | | [yellow-background]*Unknown* +
Not always present, but is an ASCII string sometimes without an end-of-string character. Maybe remnant data?
|===

....
00000000: 76 00 6f 00 05 00 00 00  90 00 00 00 00 00 00 00   v.o..... ........ 
00000010: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........ 
00000020: 01 00 00 00 74 65 73 74  00 00 00 00 74 00 65 00   ....test ....t.e. 
00000030: 73 00 74 00 00 00 73 00                            s.t...s. 
....

=== Control Panel shell item
The Control Panel shell item is 30 bytes of size and consists of the following 
values:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 2 | | The size of the shell item +
Includes the 2 bytes of the size itself
| 2 | 1 | 0x71 | Class type indicator
| 3 | 1 | | [yellow-background]*Unknown (sort order?)* +
[yellow-background]*Seen: 0x80*
| 4 | 10 | | [yellow-background]*Unknown (Empty values)*
| 14 | 16 | | Control Panel Item identifier +
Contains a GUID +
For a list of control panel identifiers see: `[LIBFWSI-WIKI]`
|===


:numbered!:
[appendix]
== References

`[HAY04]`

[cols="1,5",options="header"]
|===
| Title: | MiTeC Registry Analyser
| Author(s): | Allan S Hay
| Date: | December 2004
| URL: | http://mysite.verizon.net/hartsec/files/WRA_Guidance.pdf
|===

`[ZHU09]`

[cols="1,5",options="header"]
|===
| Title: | Using shellbag information to reconstruct user activities
| Author(s): | Yuandong Zhu, Pavel Gladyshev, Joshua James
| Date: | 2009
| URL: | http://www.dfrws.org/2009/proceedings/p69-zhu.pdf
|===

`[CHAPPEL09]`

[cols="1,5",options="header"]
|===
| Title: | RegFolder
| Author(s): | Geoff Chappel
| Date: | August 4, 2009
| URL: | http://www.geoffchappell.com/studies/windows/shell/shell32/classes/regfolder.htm
|===

`[KHATRI09]`

[cols="1,5",options="header"]
|===
| Title: | Shell BAG Format Analysis
| Author(s): | Yogesh Khatri
| Date: | October 7, 2009
| URL: | http://42llc.net/index.php?Itemid=39&=&=&option=com_myblog&show=Shell-BAG-Format.html
|===

`[LOPEZ10]`

[cols="1,5",options="header"]
|===
| Title: | LNK Parsing: You’re doing it wrong (II)
| Author(s): | Jordi Sánchez López
| Date: | August 13, 2010
| URL: | http://blog.0x01000000.org/2010/08/13/lnk-parsing-youre-doing-it-wrong-ii/
|===

`[LIBFOLE]`

[cols="1,5",options="header"]
|===
| Title: | Object Linking and Embedding (OLE) definitions
| Author(s): | Joachim Metz
| Date: | September 2009
| URL: | https://googledrive.com/host/0B3fBvzttpiiSaDZmMHFNNDgtNDA/OLE%20Definitions.pdf
|===

`[LIBFWSI-WIKI]`

[cols="1,5",options="header"]
|===
| Title: | Shell Folder Identifiers
| URL: | https://code.google.com/p/libfwsi/wiki/ShellFolderIdentifiers
|===

`[LIBFWPS]`

[cols="1,5",options="header"]
|===
| Title: | Windows Property Store format
| Author(s): | Joachim Metz
| Date: | June 2013
| URL: | https://googledrive.com/host/0B3fBvzttpiiSc3VuS1J1QmtEYzA/Windows%20Property%20Store%20format.pdf
|===

`[MSDN]`

[cols="1,5",options="header"]
|===
| Title: | Microsoft Developer Network
| URL: | http://msdn.microsoft.com/
|===

`[MSDN-CONTROLPANELCATEGORY]`

[cols="1,5",options="header"]
|===
| Title: | Assigning Control Panel Categories
| URL: | http://msdn.microsoft.com/en-us/library/windows/desktop/cc144183(v=vs.85).aspx
|===

`[MSDN-DELEGATEITEMID]`

[cols="1,5",options="header"]
|===
| Title: | DELEGATEITEMID structure
| URL: | http://msdn.microsoft.com/en-us/library/windows/desktop/bb773254(v=vs.85).aspx
|===

`[MSDN-IURI]`

[cols="1,5",options="header"]
|===
| Title: | Microsoft Developer Network - IUri Interface
| URL: | http://msdn.microsoft.com/en-us/library/ms775038.aspx +
http://msdn.microsoft.com/en-us/library/ms775141(v=vs.85).aspx +
http://msdn.microsoft.com/en-us/library/ms775140(v=vs.85).aspx +
http://msdn.microsoft.com/en-us/library/bb762576(v=vs.85).aspx
|===

`[MSDN-ITEMIDLIST]`

[cols="1,5",options="header"]
|===
| Title: | ITEMIDLIST structure
| URL: | http://msdn.microsoft.com/en-us/library/windows/desktop/bb773321(v=vs.85).aspx
|===

`[MSDN-PROPERTYKEY]`

[cols="1,5",options="header"]
|===
| Title: | PROPERTYKEY structure
| URL: | http://msdn.microsoft.com/en-us/library/windows/desktop/bb773381(v=vs.85).aspx
|===

`[MSDN-SHCOLUMNID]`

[cols="1,5",options="header"]
|===
| Title: | SHCOLUMNID structure
| URL: | http://msdn.microsoft.com/en-us/library/windows/desktop/bb759748(v=vs.85).aspx
|===

`[MSDN-SHITEMID]`

[cols="1,5",options="header"]
|===
| Title: | SHITEMID structure
| URL: | http://msdn.microsoft.com/en-us/library/windows/desktop/bb759800(v=vs.85).aspx
|===

`[MSDN-SHLNS]`

[cols="1,5",options="header"]
|===
| Title: | Introduction to the Shell Namespace
| URL: | http://msdn.microsoft.com/en-us/library/cc144090%28v=VS.85%29.aspx
|===

`[MSDN-SHELLDEV]`

[cols="1,5",options="header"]
|===
| Title: | Shell and Shlwapi DLL Versions
| URL: | http://msdn.microsoft.com/en-us/library/windows/desktop/bb776779(v=vs.85).aspx
|===

`[MSDN-WP]`

[cols="1,5",options="header"]
|===
| Title: | Windows Properties
| URL: | http://msdn.microsoft.com/en-us/library/dd561977%28v=VS.85%29.aspx
|===

[appendix]
== GNU Free Documentation License
Version 1.3, 3 November 2008
Copyright © 2000, 2001, 2002, 2007, 2008 Free Software Foundation, Inc. 
<http://fsf.org/>

Everyone is permitted to copy and distribute verbatim copies of this license 
document, but changing it is not allowed.

=== 0. PREAMBLE
The purpose of this License is to make a manual, textbook, or other functional 
and useful document "free" in the sense of freedom: to assure everyone the 
effective freedom to copy and redistribute it, with or without modifying it, 
either commercially or noncommercially. Secondarily, this License preserves for 
the author and publisher a way to get credit for their work, while not being 
considered responsible for modifications made by others.

This License is a kind of "copyleft", which means that derivative works of the 
document must themselves be free in the same sense. It complements the GNU 
General Public License, which is a copyleft license designed for free software.

We have designed this License in order to use it for manuals for free software, 
because free software needs free documentation: a free program should come with 
manuals providing the same freedoms that the software does. But this License is 
not limited to software manuals; it can be used for any textual work, 
regardless of subject matter or whether it is published as a printed book. We 
recommend this License principally for works whose purpose is instruction or 
reference.

=== 1. APPLICABILITY AND DEFINITIONS
This License applies to any manual or other work, in any medium, that contains 
a notice placed by the copyright holder saying it can be distributed under the 
terms of this License. Such a notice grants a world-wide, royalty-free license, 
unlimited in duration, to use that work under the conditions stated herein. The 
"Document", below, refers to any such manual or work. Any member of the public 
is a licensee, and is addressed as "you". You accept the license if you copy, 
modify or distribute the work in a way requiring permission under copyright law.

A "Modified Version" of the Document means any work containing the Document or 
a portion of it, either copied verbatim, or with modifications and/or 
translated into another language.

A "Secondary Section" is a named appendix or a front-matter section of the 
Document that deals exclusively with the relationship of the publishers or 
authors of the Document to the Document's overall subject (or to related 
matters) and contains nothing that could fall directly within that overall 
subject. (Thus, if the Document is in part a textbook of mathematics, a 
Secondary Section may not explain any mathematics.) The relationship could be a 
matter of historical connection with the subject or with related matters, or of 
legal, commercial, philosophical, ethical or political position regarding them.

The "Invariant Sections" are certain Secondary Sections whose titles are 
designated, as being those of Invariant Sections, in the notice that says that 
the Document is released under this License. If a section does not fit the 
above definition of Secondary then it is not allowed to be designated as 
Invariant. The Document may contain zero Invariant Sections. If the Document 
does not identify any Invariant Sections then there are none.

The "Cover Texts" are certain short passages of text that are listed, as 
Front-Cover Texts or Back-Cover Texts, in the notice that says that the 
Document is released under this License. A Front-Cover Text may be at most 5 
words, and a Back-Cover Text may be at most 25 words.

A "Transparent" copy of the Document means a machine-readable copy, represented 
in a format whose specification is available to the general public, that is 
suitable for revising the document straightforwardly with generic text editors 
or (for images composed of pixels) generic paint programs or (for drawings) 
some widely available drawing editor, and that is suitable for input to text 
formatters or for automatic translation to a variety of formats suitable for 
input to text formatters. A copy made in an otherwise Transparent file format 
whose markup, or absence of markup, has been arranged to thwart or discourage 
subsequent modification by readers is not Transparent. An image format is not 
Transparent if used for any substantial amount of text. A copy that is not 
"Transparent" is called "Opaque".

Examples of suitable formats for Transparent copies include plain ASCII without 
markup, Texinfo input format, LaTeX input format, SGML or XML using a publicly 
available DTD, and standard-conforming simple HTML, PostScript or PDF designed 
for human modification. Examples of transparent image formats include PNG, XCF 
and JPG. Opaque formats include proprietary formats that can be read and edited 
only by proprietary word processors, SGML or XML for which the DTD and/or 
processing tools are not generally available, and the machine-generated HTML, 
PostScript or PDF produced by some word processors for output purposes only.

The "Title Page" means, for a printed book, the title page itself, plus such 
following pages as are needed to hold, legibly, the material this License 
requires to appear in the title page. For works in formats which do not have 
any title page as such, "Title Page" means the text near the most prominent 
appearance of the work's title, preceding the beginning of the body of the text.

The "publisher" means any person or entity that distributes copies of the 
Document to the public.

A section "Entitled XYZ" means a named subunit of the Document whose title 
either is precisely XYZ or contains XYZ in parentheses following text that 
translates XYZ in another language. (Here XYZ stands for a specific section 
name mentioned below, such as "Acknowledgements", "Dedications", 
"Endorsements", or "History".) To "Preserve the Title" of such a section when 
you modify the Document means that it remains a section "Entitled XYZ" 
according to this definition.

The Document may include Warranty Disclaimers next to the notice which states 
that this License applies to the Document. These Warranty Disclaimers are 
considered to be included by reference in this License, but only as regards 
disclaiming warranties: any other implication that these Warranty Disclaimers 
may have is void and has no effect on the meaning of this License.

=== 2. VERBATIM COPYING
You may copy and distribute the Document in any medium, either commercially or 
noncommercially, provided that this License, the copyright notices, and the 
license notice saying this License applies to the Document are reproduced in 
all copies, and that you add no other conditions whatsoever to those of this 
License. You may not use technical measures to obstruct or control the reading 
or further copying of the copies you make or distribute. However, you may 
accept compensation in exchange for copies. If you distribute a large enough 
number of copies you must also follow the conditions in section 3.

You may also lend copies, under the same conditions stated above, and you may 
publicly display copies.

=== 3. COPYING IN QUANTITY
If you publish printed copies (or copies in media that commonly have printed 
covers) of the Document, numbering more than 100, and the Document's license 
notice requires Cover Texts, you must enclose the copies in covers that carry, 
clearly and legibly, all these Cover Texts: Front-Cover Texts on the front 
cover, and Back-Cover Texts on the back cover. Both covers must also clearly 
and legibly identify you as the publisher of these copies. The front cover must 
present the full title with all words of the title equally prominent and 
visible. You may add other material on the covers in addition. Copying with 
changes limited to the covers, as long as they preserve the title of the 
Document and satisfy these conditions, can be treated as verbatim copying in 
other respects.

If the required texts for either cover are too voluminous to fit legibly, you 
should put the first ones listed (as many as fit reasonably) on the actual 
cover, and continue the rest onto adjacent pages.

If you publish or distribute Opaque copies of the Document numbering more than 
100, you must either include a machine-readable Transparent copy along with 
each Opaque copy, or state in or with each Opaque copy a computer-network 
location from which the general network-using public has access to download 
using public-standard network protocols a complete Transparent copy of the 
Document, free of added material. If you use the latter option, you must take 
reasonably prudent steps, when you begin distribution of Opaque copies in 
quantity, to ensure that this Transparent copy will remain thus accessible at 
the stated location until at least one year after the last time you distribute 
an Opaque copy (directly or through your agents or retailers) of that edition 
to the public.

It is requested, but not required, that you contact the authors of the Document 
well before redistributing any large number of copies, to give them a chance to 
provide you with an updated version of the Document.

=== 4. MODIFICATIONS
You may copy and distribute a Modified Version of the Document under the 
conditions of sections 2 and 3 above, provided that you release the Modified 
Version under precisely this License, with the Modified Version filling the 
role of the Document, thus licensing distribution and modification of the 
Modified Version to whoever possesses a copy of it. In addition, you must do 
these things in the Modified Version:

A. Use in the Title Page (and on the covers, if any) a title distinct from that 
of the Document, and from those of previous versions (which should, if there 
were any, be listed in the History section of the Document). You may use the 
same title as a previous version if the original publisher of that version 
gives permission. 

B. List on the Title Page, as authors, one or more persons or entities 
responsible for authorship of the modifications in the Modified Version, 
together with at least five of the principal authors of the Document (all of 
its principal authors, if it has fewer than five), unless they release you from 
this requirement. 

C. State on the Title page the name of the publisher of the Modified Version, 
as the publisher. 

D. Preserve all the copyright notices of the Document. 

E. Add an appropriate copyright notice for your modifications adjacent to the 
other copyright notices. 

F. Include, immediately after the copyright notices, a license notice giving 
the public permission to use the Modified Version under the terms of this 
License, in the form shown in the Addendum below. 

G. Preserve in that license notice the full lists of Invariant Sections and 
required Cover Texts given in the Document's license notice. 

H. Include an unaltered copy of this License. 

I. Preserve the section Entitled "History", Preserve its Title, and add to it 
an item stating at least the title, year, new authors, and publisher of the 
Modified Version as given on the Title Page. If there is no section Entitled 
"History" in the Document, create one stating the title, year, authors, and 
publisher of the Document as given on its Title Page, then add an item 
describing the Modified Version as stated in the previous sentence. 

J. Preserve the network location, if any, given in the Document for public 
access to a Transparent copy of the Document, and likewise the network 
locations given in the Document for previous versions it was based on. These 
may be placed in the "History" section. You may omit a network location for a 
work that was published at least four years before the Document itself, or if 
the original publisher of the version it refers to gives permission. 

K. For any section Entitled "Acknowledgements" or "Dedications", Preserve the 
Title of the section, and preserve in the section all the substance and tone of 
each of the contributor acknowledgements and/or dedications given therein. 

L. Preserve all the Invariant Sections of the Document, unaltered in their text 
and in their titles. Section numbers or the equivalent are not considered part 
of the section titles. 

M. Delete any section Entitled "Endorsements". Such a section may not be 
included in the Modified Version. 

N. Do not retitle any existing section to be Entitled "Endorsements" or to 
conflict in title with any Invariant Section. 

O. Preserve any Warranty Disclaimers. 

If the Modified Version includes new front-matter sections or appendices that 
qualify as Secondary Sections and contain no material copied from the Document, 
you may at your option designate some or all of these sections as invariant. To 
do this, add their titles to the list of Invariant Sections in the Modified 
Version's license notice. These titles must be distinct from any other section 
titles.

You may add a section Entitled "Endorsements", provided it contains nothing but 
endorsements of your Modified Version by various parties—for example, 
statements of peer review or that the text has been approved by an organization 
as the authoritative definition of a standard.

You may add a passage of up to five words as a Front-Cover Text, and a passage 
of up to 25 words as a Back-Cover Text, to the end of the list of Cover Texts 
in the Modified Version. Only one passage of Front-Cover Text and one of 
Back-Cover Text may be added by (or through arrangements made by) any one 
entity. If the Document already includes a cover text for the same cover, 
previously added by you or by arrangement made by the same entity you are 
acting on behalf of, you may not add another; but you may replace the old one, 
on explicit permission from the previous publisher that added the old one.

The author(s) and publisher(s) of the Document do not by this License give 
permission to use their names for publicity for or to assert or imply 
endorsement of any Modified Version.

=== 5. COMBINING DOCUMENTS
You may combine the Document with other documents released under this License, 
under the terms defined in section 4 above for modified versions, provided that 
you include in the combination all of the Invariant Sections of all of the 
original documents, unmodified, and list them all as Invariant Sections of your 
combined work in its license notice, and that you preserve all their Warranty 
Disclaimers.

The combined work need only contain one copy of this License, and multiple 
identical Invariant Sections may be replaced with a single copy. If there are 
multiple Invariant Sections with the same name but different contents, make the 
title of each such section unique by adding at the end of it, in parentheses, 
the name of the original author or publisher of that section if known, or else 
a unique number. Make the same adjustment to the section titles in the list of 
Invariant Sections in the license notice of the combined work.

In the combination, you must combine any sections Entitled "History" in the 
various original documents, forming one section Entitled "History"; likewise 
combine any sections Entitled "Acknowledgements", and any sections Entitled 
"Dedications". You must delete all sections Entitled "Endorsements".

=== 6. COLLECTIONS OF DOCUMENTS
You may make a collection consisting of the Document and other documents 
released under this License, and replace the individual copies of this License 
in the various documents with a single copy that is included in the collection, 
provided that you follow the rules of this License for verbatim copying of each 
of the documents in all other respects.

You may extract a single document from such a collection, and distribute it 
individually under this License, provided you insert a copy of this License 
into the extracted document, and follow this License in all other respects 
regarding verbatim copying of that document.

=== 7. AGGREGATION WITH INDEPENDENT WORKS
A compilation of the Document or its derivatives with other separate and 
independent documents or works, in or on a volume of a storage or distribution 
medium, is called an "aggregate" if the copyright resulting from the 
compilation is not used to limit the legal rights of the compilation's users 
beyond what the individual works permit. When the Document is included in an 
aggregate, this License does not apply to the other works in the aggregate 
which are not themselves derivative works of the Document.

If the Cover Text requirement of section 3 is applicable to these copies of the 
Document, then if the Document is less than one half of the entire aggregate, 
the Document's Cover Texts may be placed on covers that bracket the Document 
within the aggregate, or the electronic equivalent of covers if the Document is 
in electronic form. Otherwise they must appear on printed covers that bracket 
the whole aggregate.

=== 8. TRANSLATION
Translation is considered a kind of modification, so you may distribute 
translations of the Document under the terms of section 4. Replacing Invariant 
Sections with translations requires special permission from their copyright 
holders, but you may include translations of some or all Invariant Sections in 
addition to the original versions of these Invariant Sections. You may include 
a translation of this License, and all the license notices in the Document, and 
any Warranty Disclaimers, provided that you also include the original English 
version of this License and the original versions of those notices and 
disclaimers. In case of a disagreement between the translation and the original 
version of this License or a notice or disclaimer, the original version will 
prevail.

If a section in the Document is Entitled "Acknowledgements", "Dedications", or 
"History", the requirement (section 4) to Preserve its Title (section 1) will 
typically require changing the actual title.

=== 9. TERMINATION
You may not copy, modify, sublicense, or distribute the Document except as 
expressly provided under this License. Any attempt otherwise to copy, modify, 
sublicense, or distribute it is void, and will automatically terminate your 
rights under this License.

However, if you cease all violation of this License, then your license from a 
particular copyright holder is reinstated (a) provisionally, unless and until 
the copyright holder explicitly and finally terminates your license, and (b) 
permanently, if the copyright holder fails to notify you of the violation by 
some reasonable means prior to 60 days after the cessation.

Moreover, your license from a particular copyright holder is reinstated 
permanently if the copyright holder notifies you of the violation by some 
reasonable means, this is the first time you have received notice of violation 
of this License (for any work) from that copyright holder, and you cure the 
violation prior to 30 days after your receipt of the notice.

Termination of your rights under this section does not terminate the licenses 
of parties who have received copies or rights from you under this License. If 
your rights have been terminated and not permanently reinstated, receipt of a 
copy of some or all of the same material does not give you any rights to use it.

=== 10. FUTURE REVISIONS OF THIS LICENSE
The Free Software Foundation may publish new, revised versions of the GNU Free 
Documentation License from time to time. Such new versions will be similar in 
spirit to the present version, but may differ in detail to address new problems 
or concerns. See http://www.gnu.org/copyleft/.

Each version of the License is given a distinguishing version number. If the 
Document specifies that a particular numbered version of this License "or any 
later version" applies to it, you have the option of following the terms and 
conditions either of that specified version or of any later version that has 
been published (not as a draft) by the Free Software Foundation. If the 
Document does not specify a version number of this License, you may choose any 
version ever published (not as a draft) by the Free Software Foundation. If the 
Document specifies that a proxy can decide which future versions of this 
License can be used, that proxy's public statement of acceptance of a version 
permanently authorizes you to choose that version for the Document.

=== 11. RELICENSING
"Massive Multiauthor Collaboration Site" (or "MMC Site") means any World Wide 
Web server that publishes copyrightable works and also provides prominent 
facilities for anybody to edit those works. A public wiki that anybody can edit 
is an example of such a server. A "Massive Multiauthor Collaboration" (or 
"MMC") contained in the site means any set of copyrightable works thus 
published on the MMC site.

"CC-BY-SA" means the Creative Commons Attribution-Share Alike 3.0 license 
published by Creative Commons Corporation, a not-for-profit corporation with a 
principal place of business in San Francisco, California, as well as future 
copyleft versions of that license published by that same organization.

"Incorporate" means to publish or republish a Document, in whole or in part, as 
part of another Document.

An MMC is "eligible for relicensing" if it is licensed under this License, and 
if all works that were first published under this License somewhere other than 
this MMC, and subsequently incorporated in whole or in part into the MMC, (1) 
had no cover texts or invariant sections, and (2) were thus incorporated prior 
to November 1, 2008.

The operator of an MMC Site may republish an MMC contained in the site under 
CC-BY-SA on the same site at any time before August 1, 2009, provided the MMC 
is eligible for relicensing.

